# Generated by Django 5.0.3 on 2024-04-14 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='weather_city',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='weather',
            name='location',
        ),
        migrations.CreateModel(
            name='weather_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('weather_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.weather_city')),
            ],
        ),
        migrations.DeleteModel(
            name='location',
        ),
        migrations.DeleteModel(
            name='weather',
        ),
    ]
