# Generated by Django 5.0.3 on 2024-04-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_weather_city_remove_weather_location_weather_temp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('temp', models.CharField(max_length=50)),
                ('pressure', models.CharField(max_length=50)),
                ('humidity', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='weather_temp',
            name='weather_city',
        ),
        migrations.DeleteModel(
            name='weather_city',
        ),
        migrations.DeleteModel(
            name='weather_temp',
        ),
    ]
